# Generated by Django 3.2.4 on 2021-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('roll_no', models.CharField(blank=True, max_length=100)),
                ('class_name', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
